## Loading Data

In [0]:
import sklearn.datasets
import numpy as np

In [0]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [0]:
X = breast_cancer.data
Y = breast_cancer.target

In [0]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [0]:
print(Y)

In [0]:
print(X.shape,Y.shape)

(569, 30) (569,)


In [0]:
import pandas as pd
#sklearn has a property feature_names which contains details of columns
data = pd.DataFrame(breast_cancer.data,columns=breast_cancer.feature_names)

In [0]:
# add a column to the dataframe
data['class']=breast_cancer.target

In [0]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [0]:
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [0]:
print(data['class'].value_counts()) # give counts of different values of the attribute

1    357
0    212
Name: class, dtype: int64


In [0]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [0]:
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

## Train and test split

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X = data.drop('class',axis=1)
Y = data['class']

In [0]:
type(Y)

pandas.core.series.Series

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y) # if ratio is not mentioned then roughly around 75% goes for training

In [0]:
print(X_train.shape,X_test.shape)

(426, 30) (143, 30)


In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.1)

In [0]:
print(X_train.shape,X_test.shape)

(512, 30) (57, 30)


In [0]:
print(Y.mean(),Y_train.mean(),Y_test.mean()) # not uniform

0.6274165202108963 0.62890625 0.6140350877192983


In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y) # maintains a uniform ratio between splits

In [0]:
print(Y.mean(),Y_train.mean(),Y_test.mean()) #uniform

0.6274165202108963 0.626953125 0.631578947368421


In [0]:
print(X.mean(),X_train.mean(),X_test.mean())

In [0]:
X_train,X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y, random_state=1)

## Binarisation of Input

In [0]:
import matplotlib.pyplot as plt
plt.plot(X_train.T,'*')
plt.xticks(rotation='vertical')
plt.show()

NameError: ignored

## Mean area varies from 0 to 2000, we are going to binarize the data. Below 1000 as 0 and above 1000 as 1


In [0]:
X_binarised_3_train = X_train['mean area'].map(lambda x: 0 if x<1000 else 1)

In [0]:
plt.plot(X_binarised_3_train)

In [0]:
plt.plot(X_test.T,'*')
plt.xticks(rotation='vertical')
plt.show()

In [0]:
plt.plot(X_binarised_3_train,'*')

In [0]:
X_binarised_train=X_train.apply(pd.cut,bins=2,labels=[1,0]) #apply function to dataframe
# since the mean value of 0 is larger than mean value of 1, labels 1 and 0 are swapped

In [0]:
plt.plot(X_binarised_train.T,'*')
plt.xticks(rotation='vertical')
plt.show()

In [0]:
X_binarised_test=X_test.apply(pd.cut,bins=2,labels=[1,0]) #apply function to dataframe

In [0]:
type(X_binarised_test)

pandas.core.frame.DataFrame

In [0]:
# Change from pandas dataframe to numpy array
X_binarised_train=X_binarised_train.values
X_binarised_test=X_binarised_test.values

In [0]:
type(X_binarised_train)

numpy.ndarray

## MP Neuron Model

In [0]:
from random import randint 
b = 3
i=randint(0,X_binarised_train.shape[0])
print('for row', i)
if (np.sum(X_binarised_train[100,:]) >= b):
  print('MP Neuron is malignant')
else:
  print('MP Neuron is benign')
if Y_train[i]==1:
  print('Truth is malignant')
else:
  print('Truth is benign')

for row 502
MP Neuron is malignant
Truth is malignant


In [0]:
from sklearn.metrics import accuracy_score

In [0]:
for b in range(X_binarised_train.shape[0]+1):
  y_pred_train = []
  accurate_rows = 0
  for x,y in zip(X_binarised_train,Y_train):
    y_pred = (np.sum(x)>=b)
    y_pred_train.append(y_pred)
    accurate_rows+=(y==y_pred)
  print(b,accurate_rows/X_binarised_train.shape[0])

In [0]:
b=28
Y_pred_test=[]
for x in X_binarised_test:
  y_pred = (np.sum(x)>=b)
  Y_pred_test.append(y_pred)
accuracy = accuracy_score(Y_pred_test, Y_test)
print(b,accuracy)

28 0.6140350877192983


## MP Neuron Class

In [0]:
class MPNeuron:
  def __init__(self):
    self.b=None

  def model(self,x):
    return(sum(x)>=self.b)

  def predict(self, X):
    Y = []
    for x in X:
      result = self.model(x)
      Y.append(result)
    return np.array(Y)

  def fit(self,X,Y):
    accuracy = {}
    for b in range(X.shape[1]+1):
      self.b = b
      Y_pred = self.predict(X)
      accuracy[b] = accuracy_score(Y_pred,Y)
    best_b = max(accuracy,key = accuracy.get)
    self.b = best_b
    print('Optimal is',best_b)
    print('Highest acc',accuracy[best_b])

In [0]:
mp = MPNeuron()
mp.fit(X_binarised_train,Y_train)

Optimal is 28
Highest acc 0.849609375


In [0]:
Y_test_pred = mp.predict(X_binarised_test)
accuracy_test = accuracy_score(Y_test_pred,Y_test)
print(accuracy_test)

0.7894736842105263
